services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: agyal
      POSTGRES_PASSWORD: agyal
      POSTGRES_DB: agyal_broker
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
